service: first-app

frameworkVersion: '3'
provider:
  name: aws
  runtime: python3.8
  region: us-east-1
  stage: ${opt:stage, 'prod'}
  memorySize: 128
  timeout: 128
  endpointType: regional
  environment:
    
custom:
  NOTES_TABLE: ${self:service}-${opt:stage, self:provider.stage}
resources:
  Resources:
    NotesTable:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Retain
      Properties:
        TableName: ${self:custom.NOTES_TABLE}
        AttributeDefinitions:
          - AttributeName: user_id
            AttributeType: S
          - AttributeName: timestamp
            AttributeType: N
          - AttributeName: note_id
            AttributeType: S
        KeySchema:
          - AttributeName: user_id
            KeyType: HASH
          - AttributeName: timestamp
            KeyType: RANGE          
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        GlobalSecondaryIndexes:
          - IndexName: note_id-index
            KeySchema:
              - AttributeName: note_id
                KeyType: HASH
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
package:
  patterns:
    - "!.env.*"
    - "!venv/**"
    - "!node_modules/**"
    - "!alembic/**"
    - "!.github/**"
    - "!package-lock.json"
    - "!package.json"
    - "!README.md"
    - "!trading-bot/**"
